apiVersion: batch/v1
kind: CronJob
metadata:
  name: gphoto-downloader
  namespace: gphoto
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: gphoto-downloader
          annotations:
            co.elastic.logs/enabled: "true"
        spec:
          containers:
            - name: gphoto-downloader
              image: singularis314/gphoto_downloader:0.4
              imagePullPolicy: Always
              env:
                - name: USERS
                  valueFrom:
                    configMapKeyRef:
                      name: users
                      key: users
              volumeMounts:
                - name: gphoto-pvc
                  mountPath: /app/static/
                - name: gphoto-credentials-pv
                  mountPath: /app/credentials/
                - name: gphoto-gcp-credentials-dante
                  mountPath: /app/gcp-credentials-dante/
                - name: gphoto-gcp-credentials-iva
                  mountPath: /app/gcp-credentials-iva/
          volumes:
            - name: gphoto-pvc
              persistentVolumeClaim:
                claimName: gphoto-pvc
            - name: gphoto-credentials-pv
              persistentVolumeClaim:
                claimName: gphoto-credentials-pv
            - name: gphoto-gcp-credentials-iva
              secret:
                secretName: gphoto-gcp-credentials-iva
                items:
                  - key: gPhoto_credentials_iva.json
                    path: gPhoto_credentials_iva.json
            - name: gphoto-gcp-credentials-dante
              secret:
                secretName: gphoto-gcp-credentials-dante
                items:
                  - key: gPhoto_credentials_dante.json
                    path: gPhoto_credentials_dante.json
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gphoto-credentials-pv
  namespace: gphoto
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /other_hdd/gphoto-credentials
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "racoon"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gphoto-credentials-pv
  namespace: gphoto
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi