apiVersion: apps/v1
kind: Deployment
metadata:
  name: gphoto-flask-deployment
  namespace: gphoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gphoto-flask
  template:
    metadata:
      labels:
        app: gphoto-flask
    spec:
      containers:
        - name: gphoto-flask
          image: singularis314/gphoto:0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: gphoto-pvc
              mountPath: /app/static/
      volumes:
        - name: gphoto-pvc
          persistentVolumeClaim:
            claimName: gphoto-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gphoto-metal-ln
  namespace: gphoto
spec:
  ports:
  - port: 448
    targetPort: 5000
    name: gphoto-flask
  selector:
    app: gphoto-flask
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gphoto-pv
  namespace: gphoto
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /other_hdd/gphoto
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "racoon"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gphoto-pvc
  namespace: gphoto
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi