---
- name: "Server configuration"
  become: yes
  hosts: localhost
  connection: local
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
    - name: Install KVM packages
      apt:
        name:
          - bridge-utils
          - cpu-checker
          - libvirt-clients
          - libvirt-daemon
        state: present
    - name: Install virt-manager
      apt:
        name:
          - virt-manager
        state: present
