---
- name: Start Rancher Server Container
  hosts: localhost
  become: true

  tasks:
    - name: Start Rancher Server Container
      community.docker.docker_container:
        name: rancher-server
        image: rancher/rancher
        privileged: true
        network_mode: host
        restart_policy: unless-stopped
        detach: true
        volumes:
          - /other:/other
          - /other_hdd:/other_hdd
