---
- name: "Main file server configuration"
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Run user bash script
    shell: |
      source ./server_configration/user_setup.sh
  - name: Run server bash script
    become: yes
    shell: |
      source ./server_configration/server_setup.sh
- name: Import basic server setup
  import_playbook: ./server_configration/basic_server_setup.yaml
- name: Import kuberentes server setup
  import_playbook: ./server_configration/kuberentes.yaml
- name: Import kuberentes server setup
  import_playbook: ./server_configration/kubeadm-config.yaml
- name: Import kvm setup
  import_playbook: ./server_configration/kvm_setup.yaml
- name: Kube setup
  import_playbook: .//kube_configration/kuberentes_setup.yaml