---
- name: "Server configuration"
  become: yes
  hosts: localhost
  connection: local 
  vars:
    openstack_release: "queens"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
        force_apt_get: yes
    - name: Install cockpit
      apt:
        name: cockpit
        state: present
    - name: Enable cockpit
      service:
        name: cockpit
        state: started
        enabled: yes
    - name: Install apparmor-utils
      apt:
        name: apparmor-utils
        state: present
    - name: Add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: Add Terraform repository
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        state: present
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Terraform
      apt:
        name: terraform
        state: present
    - name: Run Terraform version command
      command: terraform version
      register: terraform_output
    - name: Display Terraform version
      debug:
        var: terraform_output.stdout_lines
    - name: Enable AppArmor enforce mode
      command: aa-enforce /etc/apparmor.d/*
    - name: Install build-essential
      apt:
        name: build-essential
        state: present
    - name: Install git
      apt:
        name: git
        state: present
    - name: Install chrony
      apt:
        name: chrony
        state: present
    - name: Install openssh-server
      apt:
        name: openssh-server
        state: present
    - name: Install python3-dev
      apt:
        name: python3-dev
        state: present
    - name: Install sudo
      apt:
        name: sudo
        state: present
    - name: Install OpenStack
      script:
        src: ./openstack.sh