apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
  namespace: kafka-new
data:
  config.yml: |-
    kafka:
      clusters:
        - name: yaml
          bootstrapServers: 192.168.0.10:32686
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false