---
- name: Install and Configure Kafka Operator on Kubernetes
  hosts: localhost
  tasks:
    - name: Create the Kafka namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: kafka-new
        state: present

    - name: Install Strimzi Operator
      kubernetes.core.k8s:
        state: present
        namespace: kafka-new
        src: https://strimzi.io/install/latest?namespace=kafka-new

    - name: Wait for the Strimzi Operator to be ready
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: kafka-new
        name: strimzi-cluster-operator
      register: operator_status
      until: |
        operator_status.resources is defined and
        operator_status.resources | length > 0 and
        operator_status.resources[0].status.readyReplicas is defined and
        operator_status.resources[0].status.readyReplicas == 1
      retries: 60
      delay: 20

    - name: Deploy Kafka Cluster
      kubernetes.core.k8s:
        state: present
        namespace: kafka-new
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: Kafka
          metadata:
            name: kafka
          spec:
            kafka:
              replicas: 2
              listeners:
                - name: external
                  port: 9094
                  type: nodeport
                  tls: false
                  overrides:
                    bootstrap:
                      nodePort: 30092
                    brokers:
                      - broker: 0
                        nodePort: 30093
              config:
                offsets.topic.replication.factor: 1
                transaction.state.log.replication.factor: 1
                transaction.state.log.min.isr: 1
                zookeeper.session.timeout.ms: 6000
                request.timeout.ms: 6000
                controlled.shutdown.max.retries: 3
                controlled.shutdown.retry.backoff.ms: 5000
              storage:
                type: persistent-claim
                size: 2Gi
                deleteClaim: true
            zookeeper:
              replicas: 2
              config:
                initLimit: 10
                syncLimit: 5
                tickTime: 2000
                minSessionTimeout: 4000
              storage:
                type: persistent-claim
                size: 1Gi
                deleteClaim: true
            entityOperator:
              topicOperator: {}
              userOperator: {}

    - name: Create PVs for Kafka
      kubernetes.core.k8s:
        state: present
        namespace: kafka
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: "kafka-pv-{{ item }}"
          spec:
            capacity:
              storage: 2Gi
            volumeMode: Filesystem
            accessModes:
              - ReadWriteOnce
            persistentVolumeReclaimPolicy: Delete
            local:
              path: "/other/kafka/kafka-{{ item }}"
            nodeAffinity:
              required:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - "racoon"
      loop: [0,1]

    - name: Create PVs for Zookeeper
      kubernetes.core.k8s:
        state: present
        namespace: kafka
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: "zookeeper-pv-{{ item }}"
          spec:
            capacity:
              storage: 1Gi
            volumeMode: Filesystem
            accessModes:
              - ReadWriteOnce
            persistentVolumeReclaimPolicy: Delete
            local:
              path: "/other/zookeeper/zookeeper-{{ item }}"
            nodeAffinity:
              required:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - "racoon"
      loop: [0,1]

    - name: Create directories for Kafka storage
      ansible.builtin.file:
        path: "/other/kafka/kafka-{{ item }}"
        state: directory
        mode: '0755'
      loop: [0,1]

    - name: Create directories for Zookeeper storage
      ansible.builtin.file:
        path: "/other/zookeeper/zookeeper-{{ item }}"
        state: directory
        mode: '0755'
      loop: [0,1]
