---
- name: Install and Configure Kafka Operator on Kubernetes
  hosts: localhost
  tasks:
    - name: Create the Kafka namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: kafka-new
        state: present

    - name: Install Strimzi Operator
      kubernetes.core.k8s:
        state: present
        namespace: kafka-new
        src: https://strimzi.io/install/latest?namespace=kafka-new

    - name: Wait for the Strimzi Operator to be ready
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: kafka-new
        name: strimzi-cluster-operator
      register: operator_status
      until: |
        operator_status.resources is defined and
        operator_status.resources | length > 0 and
        operator_status.resources[0].status.readyReplicas is defined and
        operator_status.resources[0].status.readyReplicas == 1
      retries: 30
      delay: 10

    - name: Deploy Kafka Cluster
      kubernetes.core.k8s:
        state: present
        namespace: kafka-new
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: Kafka
          metadata:
            name: kafka
          spec:
            kafka:
              version: 3.6.1
              replicas: 3
              listeners:
                - name: plain
                  port: 9092
                  type: internal
                  tls: false
              config:
                offsets.topic.replication.factor: 3
                transaction.state.log.replication.factor: 3
                transaction.state.log.min.isr: 2
                log.message.format.version: "2.8"
              storage:
                type: ephemeral
            zookeeper:
              replicas: 2
              storage:
                type: ephemeral
            entityOperator:
              topicOperator: {}
              userOperator: {}