apiVersion: v1
kind: Service
metadata:
  name: kafka-kafka-bootstrap
  namespace: kafka-new
  labels:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: strimzi-kafka
    strimzi.io/cluster: kafka
    strimzi.io/component-type: kafka
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-kafka
spec:
  ports:
    - name: tcp-ctrlplane
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31090
    - name: tcp-replication
      protocol: TCP
      port: 9091
      targetPort: 9091
      nodePort: 31091
    - name: tcp-kafkaagent
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 31443
    - name: tcp-clients
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 31092
    - name: tcp-clientstls
      protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 31093
  selector:
    strimzi.io/cluster: kafka
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-kafka
  type: NodePort
