---
- name: Create Kafka Topics in Strimzi
  hosts: localhost
  tasks:
    - name: Create gemini-send topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: gemini-send
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create gemini-receive topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: gemini-receive
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create gpt-receive topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: gpt-receive
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create gpt-send topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: gpt-send
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create chater-aggregated topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: chater-aggregated
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create dlp-source topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: dlp-source
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create dlp-response topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: dlp-response
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create delete_food topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: delete-food
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create eater-send-photo topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: eater-send-photo
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create gemini-response topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: gemini-response
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create get_today_data topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: get-today-data
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create gpt-response topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: gpt-response
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create photo-analysis-response topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: photo-analysis-response
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create photo-analysis-response-check topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: photo-analysis-response-check
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824

    - name: Create send_today_data topic
      k8s:
        state: present
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: send-today-data
            namespace: kafka-new
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 1
            replicas: 1
            config:
              retention.ms: 300000
              segment.bytes: 1073741824