- name: Install and Configure Kafka Operator on Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create KafkaTopic
      kubernetes.core.k8s:
        state: present
        namespace: kafka-new
        definition:
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic
          metadata:
            name: chater
            labels:
              strimzi.io/cluster: kafka-new
          spec:
            partitions: 3
            replicas: 3
            config:
              retention.ms: 604800000  # 7 days
              segment.bytes: 1073741824  # 1 GiB
