---
- name: Deploy Ubuntu container with PV and PVC in Kubernetes
  hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core

  tasks:
    - name: Create development namespace
      k8s:
        name: development
        api_version: v1
        kind: Namespace
        state: present

    - name: Create PersistentVolume
      k8s:
        namespace: development
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: ubuntu-pv
          spec:
            capacity:
              storage: 5Gi
            volumeMode: Filesystem
            accessModes:
              - ReadWriteOnce
            persistentVolumeReclaimPolicy: Delete
            local:
              path: "/other/development/ubuntu"
            nodeAffinity:
              required:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - "racoon"

    - name: Create PersistentVolumeClaim
      k8s:
        namespace: development
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: ubuntu-pvc
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            volumeMode: Filesystem

    - name: Create PersistentVolume
      k8s:
        namespace: development
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: ubuntu-ssh-pv
          spec:
            capacity:
              storage: 100M
            volumeMode: Filesystem
            accessModes:
              - ReadWriteOnce
            persistentVolumeReclaimPolicy: Delete
            local:
              path: "/other/development/ubuntu/ssh"
            nodeAffinity:
              required:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - "racoon"

    - name: Create PersistentVolumeClaim
      k8s:
        namespace: development
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: ubuntu-ssh-pvc
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100M
            volumeMode: Filesystem


    - name: Start Ubuntu container as a Deployment
      k8s:
        namespace: development
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ubuntu-dev-deployment
            labels:
              app: ubuntu
              environment: development
          spec:
            replicas: 1  # Number of replicas
            selector:
              matchLabels:
                app: ubuntu
                environment: development
            template:  # Pod template
              metadata:
                labels:
                  app: ubuntu
                  environment: development
              spec:
                containers:
                  - name: ubuntu
                    image: singularis314/ubuntu_dev:0.1
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 22
                    volumeMounts:
                      - mountPath: "/home/dante/development"
                        name: ubuntu-volume
                      - mountPath: "/home/dante/.ssh"
                        name: ubuntu-ssh-volume
                volumes:
                  - name: ubuntu-volume
                    persistentVolumeClaim:
                      claimName: ubuntu-pvc
                  - name: ubuntu-ssh-volume
                    persistentVolumeClaim:
                      claimName: ubuntu-ssh-pvc

    - name: Create LoadBalancer Service for Ubuntu container
      k8s:
        namespace: development
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: ubuntu-service
          spec:
            selector:
              app: ubuntu
              environment: development
            ports:
              - protocol: TCP
                port: 22
                targetPort: 22
            type: LoadBalancer

    - name: Ensure /other/development/ubuntu directory exists
      ansible.builtin.file:
        path: /other/development/ubuntu
        state: directory
        mode: '0755'
    - name: Ensure /other/development/ubuntu/ssh directory exists
      ansible.builtin.file:
        path: /other/development/ubuntu/ssh
        state: directory
        mode: '0755'
