---
#ansible-playbook setup_kubernetes_worker.yml --ask-become-pass
- name: Setup Kubernetes Worker Nodes
  hosts: worker_nodes
  become: yes
  vars_files:
    - ../vars.yaml

  tasks:
    - name: Remove deprecated Kubernetes APT repository
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Upgrade all apt packages to the latest version
      apt:
        upgrade: dist
        state: latest

    - name: Install Python 3 and pip
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

# manual, due to approval require. Install manually.
#    - name: Download and add Kubernetes GPG key
#      shell: >
#        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key |
#        sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository to sources list
      shell: >
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' |
        sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Install Cockpit
      apt:
        name: cockpit
        state: present

    - name: Enable and start Cockpit service
      systemd:
        name: cockpit
        enabled: yes
        state: started
