image:
  repository: docker.io/vllm/vllm-openai
  tag: latest
model: "QuantTrio/Qwen3.5-9B-AWQ"
servedModelName: "QuantTrio/Qwen3.5-9B-AWQ"
gpuMemoryUtilization: "0.96"
maxModelLen: "64000"
maxNumSeqs: "4"
enableAutoToolChoice: true
toolCallParser: "qwen3_coder"
reasoningParser: "deepseek_r1"
kvCacheDtype: "fp8"
enablePrefixCaching: true
enableChunkedPrefill: true
defaultChatTemplateKwargs: '{"enable_thinking":true}'

service:
  type: LoadBalancer
  port: 8000
  loadBalancerIP: "192.168.0.160"
resources:
  limits:
    nvidia.com/gpu: 1
nodeSelector:
  kubernetes.io/hostname: racoon-gpu
