---
- name: "Main file for monitoring configuration"
  hosts: localhost
  connection: local
  gather_facts: false
- name: Setup prometheus
  import_playbook: ./prometheus_operator/prometheus.yaml
- name: Setup grafana
  import_playbook: ./grafana_operator/grafana.yaml
- name: Setup elk
  import_playbook: ./elk/elk.yaml
- name: Setup beat
  import_playbook: ./elk/beat.yaml