---
- name: Install GitLab Helm Chart
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars.yaml

  vars:
    helm_chart_repo: gitlab
    helm_chart_ref: gitlab/gitlab
    helm_chart_repo_url: https://charts.gitlab.io/
    helm_chart_release_name: gitlab
    helm_chart_namespace: "{{ vars.all.vars.ssl_namespace }}"

  tasks:
    - name: Print imported variables
      ansible.builtin.debug:
        var: vars.all.vars.gitlab
    - name: Create namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ helm_chart_namespace }}"
        state: present
    - name: Add Helm chart repository
      community.kubernetes.helm_repository:
        name: "{{ helm_chart_repo }}"
        repo_url: "{{ helm_chart_repo_url }}"

    - name: Install GitLab Helm chart
      community.kubernetes.helm:
        release_name: "{{ helm_chart_release_name }}"
        chart_ref: "{{ helm_chart_ref }}"
        namespace: "{{ helm_chart_namespace }}"
        state: present
        wait: true
        release_values:
          global:
            edition: "{{ vars.all.vars.gitlab.global_edition }}"
            hosts:
              domain: "{{ vars.all.vars.gitlab.global_hosts_domain }}"
              externalIP: "{{ vars.all.vars.gitlab.global_hosts_externalIP }}"
          certmanager-issuer:
            email: "{{ vars.all.vars.gitlab.certmanager_issuer_email }}"
          postgresql:
            image:
              tag: "{{ vars.all.vars.gitlab.postgresql_image_tag }}"
