---
- name: Configure Ngrok Ingress for a chater
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../../vars.yaml

  tasks:
    - name: Create Service for chater
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: ngrok-chater-ui
            namespace: chater-ui
          spec:
            ports:
              - name: http
                port: 5000
                targetPort: 5000
            selector:
              app: chater-ui


    - name: Create AgentEndpoint for chater domain (no TrafficPolicy)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: ngrok.k8s.ngrok.com/v1alpha1
          kind: AgentEndpoint
          metadata:
            name: chater-ui-agent-endpoint
            namespace: chater-ui
          spec:
            description: Created by Ansible - single upstream, no inline traffic policy
            upstream:
              url: http://chater-reverse-proxy.chater-ui:80
            url: "https://{{ vars.all.vars.ngrok.NGROK_DOMAIN }}"