---
- name: Configure Ngrok Ingress for a chater
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../../vars.yaml

  tasks:
    - name: Create Service for chater
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: ngrok-chater
            namespace: chater
          spec:
            ports:
              - name: http
                port: 5000
                targetPort: 5000
            selector:
              app: chater

    - name: Create Ngrok Ingress for Chater
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: chater-ngrok
            namespace: chater
          spec:
            ingressClassName: ngrok
            rules:
              - host: "{{ vars.all.vars.ngrok.NGROK_DOMAIN  }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: ngrok-chater
                          port:
                            number: 5000