---
- name: Install ngrok Helm Chart
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars.yaml

  vars:
    helm_chart_repo: ngrok
    helm_chart_ref: ngrok/kubernetes-ingress-controller
    helm_chart_repo_url: https://ngrok.github.io/kubernetes-ingress-controller
    helm_chart_release_name: ngrok-ingress-controller
    helm_chart_namespace: ngrok-ingress-controller
    apiKey: "{{ vars.all.vars.ngrok.NGROK_API_KEY }}"
    authtoken: "{{ vars.all.vars.ngrok.NGROK_AUTHTOKEN }}"

  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ helm_chart_namespace }}"
        state: present
    - name: Add Helm chart repository
      community.kubernetes.helm_repository:
        name: "{{ helm_chart_repo }}"
        repo_url: "{{ helm_chart_repo_url }}"
    - name: Install ngrok Helm chart
      community.kubernetes.helm:
        release_name: "{{ helm_chart_release_name }}"
        chart_ref: "{{ helm_chart_ref }}"
        namespace: "{{ helm_chart_namespace }}"
        update_repo_cache: true
        force: true
        wait: true
        values:
          credentials:
            apiKey: "{{ apiKey }}"
            authtoken: "{{ authtoken }}"
