---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb
spec:
  addresses:
     - 192.168.0.9-192.168.0.11
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb
  name: first-pool
spec:
  ipAddressPools:
    - first-pool