---
- name: Install harbor Helm Chart
  hosts: localhost
  gather_facts: false

  vars:
    helm_chart_repo: metallb
    helm_chart_ref: metallb/metallb
    helm_chart_repo_url: https://metallb.github.io/metallb
    helm_chart_release_name: metallb
    helm_chart_namespace: metallb

  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ helm_chart_namespace }}"
        state: present
    - name: Add Helm chart repository
      community.kubernetes.helm_repository:
        name: "{{ helm_chart_repo }}"
        repo_url: "{{ helm_chart_repo_url }}"
    - name: Install or upgrade MetalLB Helm chart to the latest version
      community.kubernetes.helm:
        release_name: "{{ helm_chart_release_name }}"
        chart_ref: "{{ helm_chart_ref }}"
        namespace: "{{ helm_chart_namespace }}"
        state: present
        update_repo_cache: true
        force: true
        wait: true
    - name: Create metalb ip pools
      command: kubectl apply -f ip_pool.yaml
