{{- if .Values.serviceAccount.createTokenSecret }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "homepage.serviceAccountName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "homepage.serviceAccountName" . }}
{{- end }}

