---
- name: "Main file server configuration"
  hosts: localhost
  connection: local
  gather_facts: false
- name: Setup kube-dashboards
  import_playbook: ./kube_dasboard/kuberentes_dasboard.yaml
- name: Setup metal-lb
  import_playbook: ./meta-lb/metal.yaml
- name: Setup ngrok
  import_playbook: ./ngrok/ngrok.yaml
- name: Setup chater-ngrok
  import_playbook: ./ngrok/chater-ngrok.yaml