---
- name: Basic Setup Playbook
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    jupyter_user: "dante"
    jupyter_home: "/home/dante/jupiter"      # Home directory for jupyter_user
    jupyter_port: 8888
    jupyter_password: "MySecret123!"
    jupyter_service_name: "jupyterlab"
    jupyter_exec_path: "/usr/local/bin/jupyter"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 600

    - name: Install init pkg
      apt:
        name:
          - fish
          - git
          - npm
          - cockpit
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: (Optional) Install Node.js and npm
      apt:
        name: nodejs
        state: present
      vars:
        ansible_debian_distribution: "{{ ansible_distribution }}"

    - name: Install "serve" globally
      npm:
        name: serve
        global: yes

    - name: Install NVIDIA utilities (nvidia-smi)
      apt:
        name:  nvidia-driver-560-open
        state: present

    - name: Install Ollama (placeholder)
      shell: |
        curl -fsSL https://ollama.com/install.sh | sh
      args:
        warn: false
