---
- name: "Main file workload configuration"
  hosts: localhost
  connection: local
  gather_facts: false
#- name: Setup gphoto
#  import_playbook: ./gphoto/gphoto.yaml
- name: Setup Kafka
  import_playbook: ./kafka/kafka.yaml
- name: Create topics
  import_playbook: ./kafka/topics.yaml
#- name: Setup chater
#  import_playbook: ./chater/chater.yaml
#- name: Create gramoxy
#  import_playbook: ./gramoxy.yaml
#- name: Create selenium
#  import_playbook: ./selenium.yaml
- name: postgres
  import_playbook: ./postgres/postgres.yaml
- name: redis
  import_playbook: ./redis/redis.yaml
- name: minio
  import_playbook: ./monio/minio.yaml
  inventory: ../inventory/kafka-cluster-inventory.ini
- name: nextcloud
  import_playbook: ./nexcloud/nexcloud.yaml
- name: open-webui
  import_playbook: ./open-webui/open-webui.yaml
- name: neo4j
  import_playbook: ./neo4j/neo4j.yaml