apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard-metal-ln
  namespace: kubernetes-dashboard
spec:
  ports:
  - port: 8443
    targetPort: 8443
    nodePort: 30443
  selector:
    k8s-app: kubernetes-dashboard
  type: NodePort